// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnvihfydlxttkichbacd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJudmloZnlkbHh0dGtpY2hiYWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mzc1ODQsImV4cCI6MjA2NTIxMzU4NH0.-h0TuyPUYtB2Ka5rCIdLZUgJhy2phEGo_XDmDE1rcnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);